//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CommunityService
{
    public CommunityService()
    {
        this.ServiceGrants = new HashSet<ServiceGrant>();
    }

    public int ServiceKey { get; set; }
    public string ServiceName { get; set; }
    public string ServiceDescription { get; set; }
    public Nullable<decimal> ServiceMaximum { get; set; }
    public Nullable<decimal> ServiceLifetimeMaximum { get; set; }

    public virtual ICollection<ServiceGrant> ServiceGrants { get; set; }
}

public partial class ServiceGrant
{
    public int GrantKey { get; set; }
    public Nullable<decimal> GrantAmount { get; set; }
    public Nullable<System.DateTime> GrantDate { get; set; }
    public Nullable<int> PersonKey { get; set; }
    public Nullable<int> ServiceKey { get; set; }
    public Nullable<int> EmployeeKey { get; set; }
    public Nullable<System.DateTime> GrantReviewDate { get; set; }
    public string GrantApprovalStatus { get; set; }
    public string GrantNeedExplanation { get; set; }
    public Nullable<decimal> GrantAllocation { get; set; }

    public virtual CommunityService CommunityService { get; set; }
}
